export const ADD_ACTION = "ADD_ACTION";
export const DEC_ACTION = "DEC_ACTION";
export const CUSTOM_CHANGE = "CUSTOM_CHANGE";

//CATEGORY TYPES
export const CATEGORY_API_REQUEST = "CATEGORY_API_REQUEST";
export const CATEGORY_API_SUCCESS = "CATEGORY_API_SUCCESS";
export const CATEGORY_API_ERROR = "CATEGORY_API_ERROR";

//MENU TYPES
export const MENU_POPULATE = "MENU_POPULATE";
